### PR TITLE
Add an option to delete missing emails from the backup folder

### PR DESCRIPTION
**Pull request by ribbons**
Emails which have been backed-up are retained in the backup even if they are deleted from the source account at a later date.  This may be undesirable as the deleted mails will re-appear when restoring from the backup.

To solve this issue, add the option `--delete-missing` (disabled by default) to delete previously backed-up emails if they are no-longer returned by the backup search query.

### CODE REVIEW

**Comment by ribbons** [comment]
Rebased against v1.11

**Comment by ribbons** [comment]
Rebased against v1.21

**Comment by jay0lee** [comment]
I appreciate the pull request, however I'm concerned users could accidentally purge the GYB backup of mail they've lost in Gmail and used GYB to protect in the first place. I'd rather see users handle this by creating a new backup. Backups are pretty quick and easy (it's the restores that take a long time).

**Comment by shantur** [comment]
This is the only feature missing in gyb than Gmvault.
I have a mailbox with 100k+ emails and backing up all after cleanup is 
1. not ideal as it needs to download everything again
2. can be an issue if your gmail access dies while you are doing a clean backup again.

Having said that, I also understand the risk that a new option might confuse the users but would you accept a new action like "backup-with-delete" or something similar to enable local deletes?

**Comment by jay0lee** [comment]
I'm struggling to find the value of such an option. GYB is a backup tool first and foremost. The fact that the backup tool has a copy of a message and the mailbox does not is a routine, expected state. If the mailbox has changed so significantly that you want to mirror it then a backup to a new folder is a relatively fast task (backup is much faster than restore.

**Comment by shantur** [comment]
The value is in case where people ( like me and @ribbons ) who are backing up the mailbox to save ourselves from a possible loss of google account (google can block you out of account) or sync between accounts.
Almost all backup tools allow the option of deleting data when deleted on source and it is just an option not mandatory. With a completely different action, it would only add to the feature list of gyb and not confuse the current users.

**Comment by ribbons** [comment]
@shantur - the patch I submitted in this PR is still maintained against the latest release of GYB over on [my fork](https://github.com/ribbons/got-your-back) and prebuilt binaries are uploaded as a GitHub Actions asset.  I can't seem to lay my hands on the documentation for who can access assets from a third party's repo so please do raise an issue in my fork if you can't see an asset on the latest build and I'll take a look at adding it as a release too.

**Comment by shantur** [comment]
@jay0lee - We are keen for this functionality to come in as part of the upstream and not to maintain forks for an optional functionality. 
Is there any way you think this optional functionality can be built in ( a different action or a super explicit option ) ?
As I understand, the reservation is that it could affect current users and this could be implemented in a way to make sure it doesn't affect current users.
All I see is this is an optional feature which just adds to the awesome feature list of gyb.
Thanks

**Comment by shantur** [comment]
Thinking more on the safety, the feature could be built with safeguard such as "don't delete if more than x% of mails are being deleted". This saves in case someone's gmail account is emptied by some attacker.

**Comment by durd** [comment]
I've run GYB for about 10 days and already wondered about this feature because I deleted 5000 old marketing emails which did not reflect on my local backup.
Shame it's not incorporated, versioning and after a certain amount of retention, deleting files that have been deleted is commonplace with backup software.

**Comment by jay0lee** [comment]
Deleting backed up emails like that would create a HUGE risk of deleting
backup data you actually need.

Just create a new backup folder at that point. The new backup won't include
the deleted emails. It means doing a new full backup but backups are
generally pretty quick to do anyway.

Jay

**Comment by bryantech** [comment]
I agree with Jay. I have been using GYB for many years after QNAP broke the
version running on my QNAP box in 2019. This is a backup tool not a
mirroring tool. I have created new backup folders in the past after
purposeful mass purges of data. I also had a malicious user delete all of
their email 20+ years of emails in 2020 upon leaving the company. GYB took
a few days to restore all of it. Thank goodness no mirroring was in effect.
3-2-1 Backup of your GYB backup folders is also a good practice.

**Comment by durd** [comment]
It's no worse than users running --purge before doing a full backup :)

It could be configurable, it's not a black/white situation (even though the PR is). For example, `--retain-deleted 365d` would only delete deleted emails older than 365days. As I mentioned, retention policies are commonplace in backup software, even enterprise email solutions are receiving the ability to apply a retention policy directly to the mailbox.

A compromise would be to mark deleted emails with another label but still keep them. That would make them easily deleted and searched for after a restore. However, the issue of Gmail space arises, if GYB has backed up all emails I've ever received and sent, but I've deleted them in Gmail, and I one day need to restore - my Gmail account might not have enough space for a restore. I use the free version of Gmail so I don't have terabytes to spread myself out on :)  
How would GYB handle that today? Does Google have a soft-limit on it's space usage?

Either way, I think ignoring deleted emails isn't feasible in the long run and I think GYB should be able to handle that.

I do have a 3-2-1 setup, but it's not made to grow indefinitely as it incurs cloud-space and therefore also a cost. It's also configured to retain versions for a specific amount of time, but always at least one version. It also backs up my TimeMachine, but I don't save any deleted TM files as Apple already has that covered within TM.

**Pull request closed without merging**
